version: '3'
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
    networks:
      - swarm
    deploy:
      placement:
        constraints: [node.role == manager]
  web:
    image: docker-compose-flask-redis-deploy_web
    networks:
      - swarm
    ports:
     - "80:5000"
    volumes:
     - .:/code
    deploy:
      mode: replicated
      replicas: 3
      labels: [app=web]
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config: 
        parallelism: 1
        delay: 10s 
        failure_action: continue
      placement:
        constraints: [node.role == manager]

networks:
  swarm:
